node {
    docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') { 
            sh 'mvn test'
        }
        stage('Deliver') {
            input message: 'Lanjutkan ke tahap Deploy? (Klik "Proceed" untuk lanjut)'
            sh './jenkins/scripts/deliver.sh'
            sh 'curl -fsSL https://railway.app/install.sh | sh'
            sh 'railway link c20b510c-483f-44a1-9eec-bac68fcb480e'
            sh 'railway up'
            sh 'sleep 1m'
        }
    }
}