node {
    docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') { 
            sh 'mvn test'
        }
        stage('Deliver') {
            input message: 'Lanjutkan ke tahap Deploy? (Klik "Proceed" untuk lanjut)'
            sh './jenkins/scripts/deliver.sh'
            sh 'su ./jenkins/scripts/install.sh'
            sh 'railway link 8349bd1c-1074-4d4c-a0db-872568fe386c'
            sh 'railway up'
            sh 'sleep 1m'
        }
    }
}